# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iv_extractor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 989)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.case_name_title_label = QtWidgets.QLabel(self.centralwidget)
        self.case_name_title_label.setGeometry(QtCore.QRect(70, 370, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.case_name_title_label.setFont(font)
        self.case_name_title_label.setObjectName("case_name_title_label")
        self.year_title_label = QtWidgets.QLabel(self.centralwidget)
        self.year_title_label.setGeometry(QtCore.QRect(80, 190, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.year_title_label.setFont(font)
        self.year_title_label.setObjectName("year_title_label")
        self.browse_file_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_file_push_button.setGeometry(QtCore.QRect(900, 80, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.browse_file_push_button.setFont(font)
        self.browse_file_push_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(192, 192, 192);\n"
"    border: 5px solid rgb(192, 192, 192);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border: 5px solid rgb(192, 192, 192);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/browsing_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_file_push_button.setIcon(icon)
        self.browse_file_push_button.setIconSize(QtCore.QSize(40, 40))
        self.browse_file_push_button.setObjectName("browse_file_push_button")
        self.failure_type_title_label = QtWidgets.QLabel(self.centralwidget)
        self.failure_type_title_label.setGeometry(QtCore.QRect(80, 630, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.failure_type_title_label.setFont(font)
        self.failure_type_title_label.setObjectName("failure_type_title_label")
        self.failure_type_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.failure_type_combo_box.setGeometry(QtCore.QRect(20, 700, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.failure_type_combo_box.setFont(font)
        self.failure_type_combo_box.setStyleSheet("QComboBox{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.failure_type_combo_box.setObjectName("failure_type_combo_box")
        self.clear_all_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_all_push_button.setGeometry(QtCore.QRect(770, 900, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.clear_all_push_button.setFont(font)
        self.clear_all_push_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(192, 192, 192);\n"
"    border: 5px solid rgb(192, 192, 192);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border: 5px solid rgb(192, 192, 192);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/trash_bin.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_all_push_button.setIcon(icon1)
        self.clear_all_push_button.setIconSize(QtCore.QSize(40, 40))
        self.clear_all_push_button.setObjectName("clear_all_push_button")
        self.run_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_push_button.setGeometry(QtCore.QRect(950, 900, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.run_push_button.setFont(font)
        self.run_push_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(192, 192, 192);\n"
"    border: 5px solid rgb(192, 192, 192);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border: 5px solid rgb(192, 192, 192);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/running.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_push_button.setIcon(icon2)
        self.run_push_button.setIconSize(QtCore.QSize(51, 51))
        self.run_push_button.setAutoDefault(False)
        self.run_push_button.setDefault(False)
        self.run_push_button.setFlat(False)
        self.run_push_button.setObjectName("run_push_button")
        self.pin_name_title_label = QtWidgets.QLabel(self.centralwidget)
        self.pin_name_title_label.setGeometry(QtCore.QRect(530, 170, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pin_name_title_label.setFont(font)
        self.pin_name_title_label.setObjectName("pin_name_title_label")
        self.browse_file_title_label = QtWidgets.QLabel(self.centralwidget)
        self.browse_file_title_label.setGeometry(QtCore.QRect(70, 8, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.browse_file_title_label.setFont(font)
        self.browse_file_title_label.setObjectName("browse_file_title_label")
        self.year_instruction_label = QtWidgets.QLabel(self.centralwidget)
        self.year_instruction_label.setGeometry(QtCore.QRect(20, 230, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.year_instruction_label.setFont(font)
        self.year_instruction_label.setObjectName("year_instruction_label")
        self.browse_file_instruction_label = QtWidgets.QLabel(self.centralwidget)
        self.browse_file_instruction_label.setGeometry(QtCore.QRect(21, 36, 1211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.browse_file_instruction_label.setFont(font)
        self.browse_file_instruction_label.setObjectName("browse_file_instruction_label")
        self.year_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.year_text_edit.setGeometry(QtCore.QRect(20, 260, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.year_text_edit.setFont(font)
        self.year_text_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.year_text_edit.setStyleSheet("QTextEdit{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.year_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.year_text_edit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.year_text_edit.setObjectName("year_text_edit")
        self.case_name_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.case_name_text_edit.setGeometry(QtCore.QRect(20, 510, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.case_name_text_edit.setFont(font)
        self.case_name_text_edit.setStyleSheet("QTextEdit{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.case_name_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.case_name_text_edit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.case_name_text_edit.setObjectName("case_name_text_edit")
        self.pin_name_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.pin_name_text_edit.setGeometry(QtCore.QRect(470, 350, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pin_name_text_edit.setFont(font)
        self.pin_name_text_edit.setStyleSheet("QTextEdit{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.pin_name_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.pin_name_text_edit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pin_name_text_edit.setObjectName("pin_name_text_edit")
        self.browse_file_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.browse_file_text_browser.setGeometry(QtCore.QRect(20, 80, 861, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.browse_file_text_browser.setFont(font)
        self.browse_file_text_browser.setStyleSheet("QTextBrowser{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:20px;\n"
"}")
        self.browse_file_text_browser.setFrameShape(QtWidgets.QFrame.Box)
        self.browse_file_text_browser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.browse_file_text_browser.setObjectName("browse_file_text_browser")
        self.failure_type_instruction_label = QtWidgets.QLabel(self.centralwidget)
        self.failure_type_instruction_label.setGeometry(QtCore.QRect(20, 670, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.failure_type_instruction_label.setFont(font)
        self.failure_type_instruction_label.setObjectName("failure_type_instruction_label")
        self.browse_file_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.browse_file_icon_label.setGeometry(QtCore.QRect(20, 0, 47, 41))
        self.browse_file_icon_label.setText("")
        self.browse_file_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/files.png"))
        self.browse_file_icon_label.setScaledContents(True)
        self.browse_file_icon_label.setObjectName("browse_file_icon_label")
        self.year_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.year_icon_label.setGeometry(QtCore.QRect(20, 180, 51, 51))
        self.year_icon_label.setText("")
        self.year_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/year.png"))
        self.year_icon_label.setScaledContents(True)
        self.year_icon_label.setObjectName("year_icon_label")
        self.case_name_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.case_name_icon_label.setGeometry(QtCore.QRect(20, 362, 51, 51))
        self.case_name_icon_label.setText("")
        self.case_name_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/case.png"))
        self.case_name_icon_label.setScaledContents(True)
        self.case_name_icon_label.setObjectName("case_name_icon_label")
        self.pin_name_instruction_label = QtWidgets.QTextBrowser(self.centralwidget)
        self.pin_name_instruction_label.setGeometry(QtCore.QRect(470, 240, 621, 111))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.pin_name_instruction_label.setFont(font)
        self.pin_name_instruction_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pin_name_instruction_label.setObjectName("pin_name_instruction_label")
        self.failure_type_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.failure_type_icon_label.setGeometry(QtCore.QRect(20, 620, 51, 51))
        self.failure_type_icon_label.setText("")
        self.failure_type_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/failure.jpg"))
        self.failure_type_icon_label.setScaledContents(True)
        self.failure_type_icon_label.setObjectName("failure_type_icon_label")
        self.pin_name_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.pin_name_icon_label.setGeometry(QtCore.QRect(470, 170, 51, 51))
        self.pin_name_icon_label.setText("")
        self.pin_name_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/3834450.png"))
        self.pin_name_icon_label.setScaledContents(True)
        self.pin_name_icon_label.setObjectName("pin_name_icon_label")
        self.case_name_instruction_label = QtWidgets.QTextEdit(self.centralwidget)
        self.case_name_instruction_label.setGeometry(QtCore.QRect(20, 410, 391, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.case_name_instruction_label.setFont(font)
        self.case_name_instruction_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.case_name_instruction_label.setReadOnly(True)
        self.case_name_instruction_label.setObjectName("case_name_instruction_label")
        self.program_status_title_label = QtWidgets.QLabel(self.centralwidget)
        self.program_status_title_label.setGeometry(QtCore.QRect(80, 840, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.program_status_title_label.setFont(font)
        self.program_status_title_label.setObjectName("program_status_title_label")
        self.program_status_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.program_status_text_browser.setGeometry(QtCore.QRect(20, 900, 731, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.program_status_text_browser.setFont(font)
        self.program_status_text_browser.setStyleSheet("QTextBrowser{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:20px;\n"
"}")
        self.program_status_text_browser.setFrameShape(QtWidgets.QFrame.Box)
        self.program_status_text_browser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.program_status_text_browser.setObjectName("program_status_text_browser")
        self.program_status_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.program_status_icon_label.setGeometry(QtCore.QRect(20, 830, 51, 51))
        self.program_status_icon_label.setText("")
        self.program_status_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/coding.png"))
        self.program_status_icon_label.setScaledContents(True)
        self.program_status_icon_label.setObjectName("program_status_icon_label")
        self.output_format_title_label = QtWidgets.QLabel(self.centralwidget)
        self.output_format_title_label.setGeometry(QtCore.QRect(530, 430, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_format_title_label.setFont(font)
        self.output_format_title_label.setObjectName("output_format_title_label")
        self.output_format_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.output_format_combo_box.setGeometry(QtCore.QRect(460, 600, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_format_combo_box.setFont(font)
        self.output_format_combo_box.setAutoFillBackground(False)
        self.output_format_combo_box.setStyleSheet("QComboBox{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.output_format_combo_box.setObjectName("output_format_combo_box")
        self.extract_iv_curve_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.extract_iv_curve_icon_label.setGeometry(QtCore.QRect(470, 430, 51, 51))
        self.extract_iv_curve_icon_label.setText("")
        self.extract_iv_curve_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/curve.png"))
        self.extract_iv_curve_icon_label.setScaledContents(True)
        self.extract_iv_curve_icon_label.setObjectName("extract_iv_curve_icon_label")
        self.overwrite_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.overwrite_combo_box.setGeometry(QtCore.QRect(810, 600, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.overwrite_combo_box.setFont(font)
        self.overwrite_combo_box.setAutoFillBackground(False)
        self.overwrite_combo_box.setStyleSheet("QComboBox{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.overwrite_combo_box.setObjectName("overwrite_combo_box")
        self.overwrite_confirmation_title_label = QtWidgets.QLabel(self.centralwidget)
        self.overwrite_confirmation_title_label.setGeometry(QtCore.QRect(870, 420, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.overwrite_confirmation_title_label.setFont(font)
        self.overwrite_confirmation_title_label.setObjectName("overwrite_confirmation_title_label")
        self.overwrite_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.overwrite_icon_label.setGeometry(QtCore.QRect(810, 430, 51, 51))
        self.overwrite_icon_label.setText("")
        self.overwrite_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/pencil.jpg"))
        self.overwrite_icon_label.setScaledContents(True)
        self.overwrite_icon_label.setObjectName("overwrite_icon_label")
        self.output_format_instruction_label = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_format_instruction_label.setGeometry(QtCore.QRect(460, 500, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.output_format_instruction_label.setFont(font)
        self.output_format_instruction_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.output_format_instruction_label.setObjectName("output_format_instruction_label")
        self.overwrite_instruction_label = QtWidgets.QTextBrowser(self.centralwidget)
        self.overwrite_instruction_label.setGeometry(QtCore.QRect(810, 490, 291, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.overwrite_instruction_label.setFont(font)
        self.overwrite_instruction_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.overwrite_instruction_label.setObjectName("overwrite_instruction_label")
        self.open_result_in_website_label = QtWidgets.QLabel(self.centralwidget)
        self.open_result_in_website_label.setGeometry(QtCore.QRect(520, 700, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.open_result_in_website_label.setFont(font)
        self.open_result_in_website_label.setObjectName("open_result_in_website_label")
        self.open_result_in_website_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.open_result_in_website_icon_label.setGeometry(QtCore.QRect(460, 700, 51, 51))
        self.open_result_in_website_icon_label.setText("")
        self.open_result_in_website_icon_label.setPixmap(QtGui.QPixmap(":/icon/icons/Network-Domain-icon.png"))
        self.open_result_in_website_icon_label.setScaledContents(True)
        self.open_result_in_website_icon_label.setObjectName("open_result_in_website_icon_label")
        self.open_the_result_in_website_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.open_the_result_in_website_combo_box.setGeometry(QtCore.QRect(460, 790, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.open_the_result_in_website_combo_box.setFont(font)
        self.open_the_result_in_website_combo_box.setAutoFillBackground(False)
        self.open_the_result_in_website_combo_box.setStyleSheet("QComboBox{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.open_the_result_in_website_combo_box.setObjectName("open_the_result_in_website_combo_box")
        self.include_the_original_result_files_label = QtWidgets.QLabel(self.centralwidget)
        self.include_the_original_result_files_label.setGeometry(QtCore.QRect(880, 690, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.include_the_original_result_files_label.setFont(font)
        self.include_the_original_result_files_label.setObjectName("include_the_original_result_files_label")
        self.include_the_original_result_files_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.include_the_original_result_files_combo_box.setGeometry(QtCore.QRect(810, 790, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.include_the_original_result_files_combo_box.setFont(font)
        self.include_the_original_result_files_combo_box.setAutoFillBackground(False)
        self.include_the_original_result_files_combo_box.setStyleSheet("QComboBox{\n"
"    background-color: rgb(178, 190, 181);\n"
"    border: 5px solid rgb(178, 190, 181);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.include_the_original_result_files_combo_box.setObjectName("include_the_original_result_files_combo_box")
        self.include_the_original_result_files_icon = QtWidgets.QLabel(self.centralwidget)
        self.include_the_original_result_files_icon.setGeometry(QtCore.QRect(800, 700, 71, 71))
        self.include_the_original_result_files_icon.setText("")
        self.include_the_original_result_files_icon.setPixmap(QtGui.QPixmap(":/icon/icons/computer-icons-product-manuals-owner-s-manual-icon-design-symbol-png-favpng-1qGtx1MGghGVNaqNYTM4BWAhD.jpg"))
        self.include_the_original_result_files_icon.setScaledContents(True)
        self.include_the_original_result_files_icon.setObjectName("include_the_original_result_files_icon")
        self.overwrite_instruction_label.raise_()
        self.output_format_instruction_label.raise_()
        self.case_name_title_label.raise_()
        self.year_title_label.raise_()
        self.browse_file_push_button.raise_()
        self.failure_type_title_label.raise_()
        self.failure_type_combo_box.raise_()
        self.clear_all_push_button.raise_()
        self.run_push_button.raise_()
        self.pin_name_title_label.raise_()
        self.browse_file_title_label.raise_()
        self.year_instruction_label.raise_()
        self.browse_file_instruction_label.raise_()
        self.year_text_edit.raise_()
        self.case_name_text_edit.raise_()
        self.pin_name_text_edit.raise_()
        self.browse_file_text_browser.raise_()
        self.failure_type_instruction_label.raise_()
        self.browse_file_icon_label.raise_()
        self.year_icon_label.raise_()
        self.case_name_icon_label.raise_()
        self.pin_name_instruction_label.raise_()
        self.failure_type_icon_label.raise_()
        self.pin_name_icon_label.raise_()
        self.case_name_instruction_label.raise_()
        self.program_status_title_label.raise_()
        self.program_status_text_browser.raise_()
        self.program_status_icon_label.raise_()
        self.output_format_title_label.raise_()
        self.output_format_combo_box.raise_()
        self.extract_iv_curve_icon_label.raise_()
        self.overwrite_combo_box.raise_()
        self.overwrite_confirmation_title_label.raise_()
        self.overwrite_icon_label.raise_()
        self.open_result_in_website_label.raise_()
        self.open_result_in_website_icon_label.raise_()
        self.open_the_result_in_website_combo_box.raise_()
        self.include_the_original_result_files_label.raise_()
        self.include_the_original_result_files_combo_box.raise_()
        self.include_the_original_result_files_icon.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.case_name_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#36454f;\">Case Name:</span></p></body></html>"))
        self.year_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#36454f;\">Year:</span></p></body></html>"))
        self.browse_file_push_button.setText(_translate("MainWindow", "Browse Folder"))
        self.failure_type_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#36454f;\">Failure Type:</span></p></body></html>"))
        self.clear_all_push_button.setText(_translate("MainWindow", "Clear All"))
        self.run_push_button.setText(_translate("MainWindow", "Run"))
        self.pin_name_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#36454f;\">Pin Names:</span></p></body></html>"))
        self.browse_file_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#36454f;\">Browse the storing location:</span></p></body></html>"))
        self.year_instruction_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:normal; color:#36454f;\">Example: 2024</span></p></body></html>"))
        self.browse_file_instruction_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#36454f;\">Click the &quot;Browse Folder&quot; button and choose a directory on your system</span></p></body></html>"))
        self.year_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:400;\"><br /></p></body></html>"))
        self.case_name_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:400;\"><br /></p></body></html>"))
        self.pin_name_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:400;\"><br /></p></body></html>"))
        self.browse_file_text_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.failure_type_instruction_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:normal; color:#36454f;\">Select the failure from the drop down box</span></p></body></html>"))
        self.pin_name_instruction_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:10pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:normal; color:#36454f;\">Specify which pins that need failure analysis based on the position in the commonality list.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:normal; color:#36454f;\">- Example for one case: [AY44, AK22]</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:normal; color:#36454f;\">- Example for multiple cases: [AY43, AY44], [AK21, AK22],....</span></p></body></html>"))
        self.case_name_instruction_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; color:#36454f;\">Input the desired case name(s). The product names are optional.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; color:#36454f;\">Example:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; color:#36454f;\">- For a single case: CI2415-1234 TGP</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; color:#36454f;\">- For multiple cases: CI2402-2080, CI2403-2483,...</span></p></body></html>"))
        self.program_status_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#36454f;\">Program Status:</span></p><p><br/></p></body></html>"))
        self.program_status_text_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.output_format_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#36454f;\">Output Format</span><br/></p></body></html>"))
        self.overwrite_confirmation_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#36454f;\">Overwrite Confirmation</span></p></body></html>"))
        self.output_format_instruction_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:10pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:normal; color:#36454f;\">Choose whether:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:normal; color:#36454f;\">- Have a commonality analysis result as a text file.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:normal; color:#36454f;\">- Have IV Curve images of the specified pins.</span></p></body></html>"))
        self.overwrite_instruction_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:10pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; color:#36454f;\">Only for &quot;Commonality analysis text file&quot; option:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:normal; color:#36454f;\">- &quot;Yes&quot; for deleting the old result and writing the new result.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-style:normal; color:#36454f;\">- &quot;No&quot; for adding the new result to the old result. </span></p></body></html>"))
        self.open_result_in_website_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#36454f;\">Open the result </span></p><p><span style=\" color:#36454f;\">in webiste</span></p><p><br/></p></body></html>"))
        self.include_the_original_result_files_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#36454f;\">Include the original</span></p><p>result files</p><p><br/></p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
